sudo: required

dist: trusty

services:
  - docker

env:
  global:
    - secure: "goRkLb3NjaRYkgjWTpBp5QFd4vC/rLcXbh5l54oW2QkF5as16E4zimz6KKSsa1aUz0cjqbj1pnfhwIHwJfbtYe6T3nKoc6lY0+U0wdFmuNUm0FTBTQnaWubIQE2IjlXDrYvbM8JddYsjHxGe+7ci57tnIZIDeH/a4wlOT0WWsvGW20foRsrtjkMpfIs1h4QDHOEXHlLjIkXKNoibAyP4t4EnUrsVuculs/9eIIxjbIg3FJUZ4S5yNIYf56iWnzYuvSlyxBha57EBeZdBNt+LBjyHsbLYdt3CzeWae8XbID4n6o9+5N6tBJWPqLYy/715LDStpO1qZqusHOqSrxotJ7ttMhoRXohDrts9a4cOL92h7eo3/BE9y933pVEEWiYu10INrXbnb0ylPFyt1fNNzQQ/j8QVGY6xNxT3KuKTA/2e8WdMitrWOnm4slB++MqxehHdALrENa0bKmogAf1oT0eAguiV3Ad3hS2zYnLAqRpL3Iiwmyx0C6jboUxOZOCCq/j1CKF2AvqgBcuCPZIEUrAfAziJ3BRmWmY9Ml7Xz213szgQUm/+4ZYDsG8GLuF0KE86kbLtCRbER7KhvrAVjaof1GK+BI9SOwVv6x3jVs37STqfO2ESWxz8RMQyLVfjzhAGRjZ039juu7bqjSOgtgmuZtj2oU3NYoTdqAgWrvY="

before_script:
  - docker pull "brisbanebirdteam/build-env:latest"

script:
  - echo GITHUB_PAT=$GITHUB_PAT >> $HOME/.Renviron
  - sudo fallocate -l 9G /swapfile && sudo chmod 600 /swapfile && sudo mkswap /swapfile && sudo swapon /swapfile
  - make pull_assets
  - travis_wait 120 make book_pdf
  - make deploy_book_pdf

notifications:
  email:
    on_success: change
    on_failure: change 
